package model;

import java.sql.Date;

public class Classroom {
    private int classId;
    private String className;
    private String classCode;
    private String classDescription;
    private int userId; // The Educator who owns it
    private Date createdDate;

    // Empty Constructor
    public Classroom() {}

    // Constructor for creating a NEW class
    public Classroom(String className, String classDescription, int userId) {
        this.className = className;
        this.classDescription = classDescription;
        this.userId = userId;
        // classCode will be generated by the DAO!
    }

    // --- Getters and Setters ---
    public int getClassId() { return classId; }
    public void setClassId(int classId) { this.classId = classId; }

    public String getClassName() { return className; }
    public void setClassName(String className) { this.className = className; }

    public String getClassCode() { return classCode; }
    public void setClassCode(String classCode) { this.classCode = classCode; }

    public String getClassDescription() { return classDescription; }
    public void setClassDescription(String classDescription) { this.classDescription = classDescription; }

    public int getUserId() { return userId; }
    public void setUserId(int userId) { this.userId = userId; }

    public Date getCreatedDate() { return createdDate; }
    public void setCreatedDate(Date createdDate) { this.createdDate = createdDate; }
}